// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgTlZ9DqWbRUQcF7EvqFYEPoCZAZrLK5U',
    appId: '1:361809157393:web:8ece7ead34b418c76100b0',
    messagingSenderId: '361809157393',
    projectId: 'bab-e-ilm',
    authDomain: 'bab-e-ilm.firebaseapp.com',
    storageBucket: 'bab-e-ilm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtax0q1hgk3lq_v7mdIoBeeigAxO4IwO8',
    appId: '1:361809157393:android:e1fb6cc7c010aa1d6100b0',
    messagingSenderId: '361809157393',
    projectId: 'bab-e-ilm',
    storageBucket: 'bab-e-ilm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr4qaWFgdeyG8QqwIR220z2aFdbXxQ428',
    appId: '1:361809157393:ios:7631fadd9bf03f4b6100b0',
    messagingSenderId: '361809157393',
    projectId: 'bab-e-ilm',
    storageBucket: 'bab-e-ilm.appspot.com',
    iosClientId: '361809157393-2l9vidcuk3vin3fh3hctfu5cio8nqq9g.apps.googleusercontent.com',
    iosBundleId: 'com.burhansherkatha.babeilm.babEIlm',
  );
}
